services:
  # REST API Browser as the primary app
  api-browser:
    build:
      context: ./rest-api-browser
      dockerfile: Dockerfile
    image: netsuite-api-browser:latest
    container_name: netsuite-api-browser
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ACCOUNT_ID=${ACCOUNT_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=http://localhost:3000/callback
      - TZ=America/Chicago
    volumes:
      # For persisting tokens between container restarts
      - token-data:/app/tokens
    networks:
      - netsuite-network

volumes:
  token-data:

networks:
  netsuite-network:
    driver: bridge 